version: "3.6"
services:
    app:
        build:
            context: ./..
            dockerfile: EmployeeMap.App/Dockerfile
        depends_on:
            - api
        environment:
            api__root: http://EmployeeMapApi/api/
        hostname: employeemap
    api:
        build:
            context: ./..
            dockerfile: EmployeeMap.Api/Dockerfile
        env_file:
            - .env
        ports:
            - "8000:80"
        depends_on:
            - db
        hostname: employeemapapi
    db:
        build:
            context: ./..
            dockerfile: EmployeeMap.Data/Dockerfile
        env_file:
            - .env
networks:
  default:
    external:
      name: nat