version: '3.6'

services:
  employeemap.api:
    image: employeemap.api:debug

    ports:
      - "80"
      - "4022:4022"

    hostname: employeemapapi

    env_file:
        - .env

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      - NUGET_FALLBACK_PACKAGES=C:\.nuget\fallbackpackages

    volumes:
      - C:\Users\nswimberghe\projects\EmployeeMap\EmployeeMap.Api\:C:\FullApp\EmployeeMap.Api:rw
      - C:\Users\nswimberghe\projects\EmployeeMap\EmployeeMap.Data\:C:\FullApp\EmployeeMap.Data:rw
      - C:\Users\nswimberghe\onecoremsvsmon\15.0.27428.1:C:\remote_debugger:ro
      - C:\Users\nswimberghe\.nuget\packages\:C:\.nuget\packages
      - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:C:\.nuget\fallbackpackages

    build:
      context: ..
      dockerfile: EmployeeMap.Api\Dockerfile.Debug

    entrypoint: dotnet run --no-launch-profile

    working_dir: \FullApp\employeeMap.Api

    depends_on:
        - db

  employeemap.app:
    image: employeemap.app:debug

    ports:
      - "80"
      - "4021:4022"
      - "5001:5001"

    hostname: employeemap

    env_file:
        - .env

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      - NUGET_FALLBACK_PACKAGES=C:\.nuget\fallbackpackages

    volumes:
      - C:\Users\nswimberghe\projects\EmployeeMap\employeeMap.App:C:\FullApp:rw
      - C:\Users\nswimberghe\onecoremsvsmon\15.0.27428.1:C:\remote_debugger:ro
      - C:\Users\nswimberghe\.nuget\packages\:C:\.nuget\packages:ro
      - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:C:\.nuget\fallbackpackages

    build:
      context: ..
      dockerfile: EmployeeMap.App\Dockerfile.Debug

    entrypoint: dotnet run --no-launch-profile

    working_dir: G:\\

  db:
      image: employeemap.data:debug
      build:
          context: ..
          dockerfile: EmployeeMap.Data/Dockerfile
      env_file:
          - .env
networks:
  default:
    external:
      name: nat